### ISSUE TITLE
Version number missing from cover page

### ISSUE THREAD

**Issue by ghobona** [metanorma/mn-templates-ogc#11]
The cover page of an OGC standard should show the version number amongst other document metadata.

<img width="1388" alt="Screen Shot 2019-12-14 at 13 34 03" src="https://user-images.githubusercontent.com/18121038/70849452-79672b00-1e76-11ea-9187-eba031ffcc7e.png">

**Comment by ronaldtse** [comment]
@ghobona thanks for the report. We will get that done soon.

ping @opoudjis

**Comment by opoudjis** [comment]
Adding to HTML cover page before additional formats, with the other document identifiers and URLs. The version will be entered in the document template as `:edition:`, for consistency with the rest of OGC, but will be displayed as "Version" (but only if supplied).

**Comment by opoudjis** [comment]
Note that this information was already in the Word title page; it was only missing from the HTML title page.
