### ISSUE TITLE
Update OGC templates according to metanorma/metanorma.com#190

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-ogc#12]
https://github.com/metanorma/metanorma.com/pull/190

Shows the new list of `:doctype:`s and `:docsubtype:`s. We need to fill in the necessary templates.

**Comment by manuelfuenmayor** [comment]
@ronaldtse, first off, sorry for the delay in this task, it won't happen again. 
On the other hand, I don't see any list in metanorma/metanorma.com#190. Do you mean the list shown in https://github.com/metanorma/metanorma-ogc/issues/58?

**Comment by ronaldtse** [comment]
@manuel489 I did mean the original one:
<img width="547" alt="Screen Shot 2020-03-06 at 3 25 24 AM" src="https://user-images.githubusercontent.com/11865/76017777-1effd700-5f5a-11ea-81ba-0e4a303a20c0.png">

But it's better to use this list:
https://www.metanorma.com/author/ogc/authoring/

:doctype: Mandatory. Document type.
* standard: Standard (a document subtype is necessary, see [ogc-docsubtype]) (default)
* abstract-specification-topic: Abstract Specification
* best-practice: Best Practice (a document subtype is necessary, see [ogc-docsubtype])
* change-request-supporting-document: Change Request Supporting Document
* community-practice: Community Practice
* community-standard: Community Standard
* discussion-paper: Discussion Paper
* engineering-report: Engineering Report
* other: Note, Primer, etc.
* policy: Policy, Policy — Name Type Specification
* reference-model: Reference Model
* release-notes: Release Notes
* test-suite: Test Suite
* user-guide: User Guide
* white-paper: White Paper

:docsubtype: Document subtype.

For doctype set to standard:
* implementation: Implementation (default)
* conceptual-model: Conceptual model
* conceptual-model-and-encoding: Conceptual model and encoding
* conceptual-model-and-implementation: Conceptual model and implementation
* encoding: Encoding
* extension: Extension
* profile: Profile
* profile-with-extension: Profile with extension

For doctype set to best-practice:
* general: General (default)
* encoding: Encoding
* extension: Extension
* profile: Profile
* profile-with-extension: Profile with extension

**Comment by manuelfuenmayor** [comment]
standard-implementation template added in https://github.com/metanorma/mn-templates-ogc/pull/15

**Comment by manuelfuenmayor** [comment]
community-standard template added in https://github.com/metanorma/mn-templates-ogc/pull/16

**Comment by manuelfuenmayor** [comment]
test-suite template added in https://github.com/metanorma/mn-templates-ogc/pull/24

**Comment by manuelfuenmayor** [comment]
### List of OGC templates:

- [x] standard: Standard (a document subtype is necessary, see [ogc-docsubtype]) (default)
- [x] abstract-specification-topic: Abstract Specification
- [x] best-practice: Best Practice (a document subtype is necessary, see [ogc-docsubtype])
- [ ] ~~change-request-supporting-document: Change Request Supporting Document~~ -- *No sample yet*
- [ ] ~~community-practice: Community Practice~~ -- *No sample yet*
- [x] community-standard: Community Standard
- [x] discussion-paper: Discussion Paper
- [x] engineering-report: Engineering Report
- [x] other: Note, Primer, etc.
- [x] policy: Policy, Policy — Name Type Specification
- [x] reference-model: Reference Model
- [x] release-notes: Release Notes
- [x] test-suite: Test Suite
- [x] user-guide: User Guide
- [x] white-paper: White Paper

**Comment by manuelfuenmayor** [comment]
discussion-paper updated in https://github.com/metanorma/mn-templates-ogc/pull/23

**Comment by manuelfuenmayor** [comment]
abstract-specification-topic template added in https://github.com/metanorma/mn-templates-ogc/pull/25

**Comment by manuelfuenmayor** [comment]
Annotations added to `best-practice`, `release-notes`, and `white-papers` templates in https://github.com/metanorma/mn-templates-ogc/pull/26

**Comment by manuelfuenmayor** [comment]
Added: `primer`, `policy`, `reference-model`, and `user-guide` templates in https://github.com/metanorma/mn-templates-ogc/pull/30

**Comment by manuelfuenmayor** [comment]
Task is merged. Closing.
