### ISSUE TITLE
Create "Community Practice" document type template

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-ogc#13]
Create a CP template in OGC templates.

ping @manuel489

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-ogc/issues/54#issuecomment-563510055_

**Comment by manuelfuenmayor** [comment]
Hi @ronaldtse , I can't find a Community Practice doc sample I can take guidance from. Do you have one?

**Comment by ronaldtse** [comment]
@manuel489 there is no Community Practice document yet right now, the first one is only starting to get developed. Let's put this task on hold for now.

**Comment by manuelfuenmayor** [comment]
Ping @ronaldtse
No Community Practice document yet?

**Comment by ronaldtse** [comment]
@manuel489 can you please help convert this document 18-095r7? Thanks! 

https://www.ogc.org/docs/cp

**Comment by ronaldtse** [comment]
Ie. Convert and move to mn-samples-ogc. Extract the template and place it here.

**Comment by ronaldtse** [comment]
@manuel489 this one is already done and merged? https://github.com/metanorma/mn-samples-ogc/pull/123

**Comment by ronaldtse** [comment]
Ah!! Template. Sorry. Can you help us do it? Thanks.

**Comment by manuelfuenmayor** [comment]
> Ah!! Template. Sorry. Can you help us do it? Thanks.

@ronaldtse, Community Practice template is pushed in https://github.com/metanorma/mn-templates-ogc/pull/42

**Comment by ronaldtse** [comment]
Merged.
