### ISSUE TITLE
Create document templates according to OGC document types

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-ogc#14]
Task is to copy documents from mn-samples-ogc, one for each document type, place them here and strip them of information so that they are "templates".

Before that we need to handle #12 to update the README in this repository.

**Comment by manuelfuenmayor** [comment]
community-standard template added in https://github.com/metanorma/mn-templates-ogc/pull/16 (first pass)

**Comment by manuelfuenmayor** [comment]
For the record, I believe this ticket is practically the same as this one: https://github.com/metanorma/mn-templates-ogc/issues/12

I'm working on this.

**Comment by manuelfuenmayor** [comment]
Task completed in https://github.com/metanorma/mn-templates-ogc/issues/12. Closing.
