### ISSUE TITLE
`standard` template generates without clause 4

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-ogc#2]
See ToC:

<img width="220" alt="image" src="https://user-images.githubusercontent.com/11865/55349052-47ca5180-54eb-11e9-9067-02e90e05d445.png">

But technically, it does have clause 4.1.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/11865/55349070-56b10400-54eb-11e9-86f6-daeba7da1f4c.png">

Very strange.

**Comment by opoudjis** [comment]
Fixed in https://github.com/metanorma/metanorma-ogc/issues/30: Conformance section was being counted twice, even if displayed once.
